config/routes.rb
Sandbox::Application.routes.draw do

  get 'about' => 'pages#about'
  get 'projects' => 'pages#projects'
  get 'getinfo' => 'pages#getinfo'
  
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def getinfo
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="row-fluid">
	<div class="span6 offset9">
		  <small>
		 	Web design by Carry Lab
		  </small>
	</div>  
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">

			<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			 
			<!-- Be sure to leave the brand out there if you want it shown -->
			<%= link_to "SANDBOX", root_path, class: "brand" %>
			 
			<!-- Everything you want hidden at 940px or less, place within here -->

				<div class="nav-collapse collapse">
						<ul class="nav">
							<li><%= link_to "HOME", root_path %></li>
							<li><%= link_to "ABOUT", about_path %></li>
							<li><%= link_to "PROJECTS", projects_path %></li>
						</ul>
				</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>sandbox</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
  <%= metamagic %>
</head>
<body>
  <%= render 'layouts/header' %>
<%= yield %>
  <div class="container">
    <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/getinfo.html.erb
		<%
			meta :title => "Sandbox | Get Info",
     :description => "This would be a page where visitors could sign up to get more info.",
     :keywords => %w(Sandbox Sign Up, Contact)
		%>
			

			<center><a name="form1885999725" id="formAnchor1885999725"></a>
			<script type="text/javascript" src="http://fs4.formsite.com/include/form/embedManager.js?1885999725"></script>
			<script type="text/javascript">
			EmbedManager.embed({
				key: "http://fs4.formsite.com/res/showFormEmbed?EParam=PyBo85CFjhGa8v4RxfxGR8d%2FCVfYhMrF&1885999725",
				width: "50%"
			});
			</script><center>
			<!-- Notes: 
			To control the width of the form, change width: "100%" to any number or percentage.
			To pre-populate fields in the form or to use a custom resize callback, see http://fs4.formsite.com/documentation/embedded-form.html
			-->

app/views/pages/home.html.erb
<%
meta :title => "Sandbox | Homepage",
     :description => "Sandbox is the app where cool things are tested.",
     :keywords => %w(RoR, Ruby Gems, Web Development)
%>

<script type="text/javascript">
  $(document).ready(function() {
    $('.carousel').carousel({
      interval: 3000
    })
  });
</script>

<div class="container">

	<div id="this-carousel-id" class="carousel slide">
			<div class="carousel-inner">
					<div class="item active">
						<img src="https://lh5.googleusercontent.com/oGG6BB8xge2HVtBePk15YkHqdFsyAfc7cbr32FG8N7nwppj5tdYd7TXwCjapO5Kac5YsTxmNo91TaoH09hlcCeS-agcpR2Agb-czT1UVNFtJfggr4svLVrFn" alt="image 1" /> 
							<div  class="carousel-caption">
								<p>caption text here</p>
							</div>
					</div>
					<div class="item">
						<img src="https://lh5.googleusercontent.com/oGG6BB8xge2HVtBePk15YkHqdFsyAfc7cbr32FG8N7nwppj5tdYd7TXwCjapO5Kac5YsTxmNo91TaoH09hlcCeS-agcpR2Agb-czT1UVNFtJfggr4svLVrFn" alt="image 2" /> 
							<div  class="carousel-caption">
								<p>caption text here</p>
							</div>
					</div>
				 	<div class="item">
						<img src="https://lh5.googleusercontent.com/oGG6BB8xge2HVtBePk15YkHqdFsyAfc7cbr32FG8N7nwppj5tdYd7TXwCjapO5Kac5YsTxmNo91TaoH09hlcCeS-agcpR2Agb-czT1UVNFtJfggr4svLVrFn" alt="image 3" /> 
							<div  class="carousel-caption">
								<p>caption text here</p>
							</div>
					 </div>
			</div> <!-- /.carousel-inner -->

					<a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
					<a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
	</div>

			<div class="center well well-large">
					<div class="row-fluid">
					  <div class="span4">
					  	<h4>PROMO SPOT 1</h4>
					  	<p>more text</p>
					  </div>
					  <div class="span4">
					  	<h4><%= link_to "PROMO SPOT 2", getinfo_path , :class => "links"%></h4>
					  </div>
					  <div class="span4">
					  	<h4>PROMO SPOT 3</h4>
					  	<p>more text</p>
				  </div>
			</div>
</div>